//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsAlgo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagsMatchPerecent
    {
        public string FirstTag { get; set; }
        public string SecondTag { get; set; }
        public int AtLeastOneTagAppear { get; set; }
        public int BothTagsAppear { get; set; }
        public double MatchPercent { get; set; }
        public int Id { get; set; }
    }
}
